name: minipix
root: ./
startup_window: main
windows:
  - main:
      layout: even-vertical
      pre_window: echo pes
      panes:
        - ./minipix_dummy /dev/ttyUSB0 921600 0 `pwd`/dummy_data
        - sleep 1; ./gatherer /dev/ttyUSB1 921600 0
