name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**.yaml'
      - '**.launch'

  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch the whole history

      - name: Build
        run: ./.ci/build.sh
