name: Build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  schedule:
    - cron:  '0 0 * * *' # at the end of every day

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch the whole history

      - name: Build
        run: ./.ci/build.sh
